FROM node:alpine as base
WORKDIR /app
COPY package.json package-lock.json ./

FROM base as test
RUN npm i
COPY . .
RUN npm run test

FROM base as prod
RUN npm i --production
COPY . .
CMD ["npm", "run", "start"]

# need to recreate image and then run
