version: '3.7'
services:
  app:
    image: leawn/frontend
    command: sh -c "npm install && npm run start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
  tests:
    image: leawn/frontend
    command: sh -c "npm run test"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
