version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: redis:latest
  server:
    image: leawn/fibonacci-calc-server
    command: sh -c "npm install && npm run start"
    working_dir: /app
    volumes:
      - ./server/:/app