apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: leawn/mini-micro-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: leawn/mini-micro-comments
        context: comments
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: '*.js'
              dest: .
    - image: leawn/mini-micro-event-bus
        context: event-bus
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: '*.js'
              dest: .
    - image: leawn/mini-micro-moderation
        context: moderation
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: '*.js'
              dest: .
    - image: leawn/mini-micro-posts
        context: posts
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: '*.js'
              dest: .
    - image: leawn/mini-micro-query
        context: query
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: '*.js'
              dest: .