version: '3'
services:
  web:
    container_name: web
    build:
      context: ../.
      dockerfile: docker/app/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - '.:/app'
      - '/app/node_modules'
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true